name: check linting

on:
  pull_request:
    branches: [master]

jobs:
  test_linting:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint